/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CollectionsManager } from "./CollectionsManager";
export type { Errors } from "./Errors";
export type { Size } from "./Size";
export type { SizeFactory } from "./SizeFactory";
export * as factories from "./factories";
export { CollectionsManager__factory } from "./factories/CollectionsManager__factory";
export { Errors__factory } from "./factories/Errors__factory";
export { Size__factory } from "./factories/Size__factory";
export { SizeFactory__factory } from "./factories/SizeFactory__factory";
